# Generated by Django 4.1.3 on 2022-12-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('NONE', 'NONE'), ('2W', 'Two Wheeler'), ('4W', 'Four Wheeler')], default='KTM', max_length=5),
        ),
    ]
