# Generated by Django 4.1.3 on 2022-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='city',
            field=models.CharField(choices=[('SHR', 'Shared'), ('SEP', 'Separated')], default='SEP', max_length=5),
        ),
    ]
