# Generated by Django 4.1.3 on 2022-12-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_city_bathroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
