# Generated by Django 4.1.3 on 2022-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_kitchen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='type',
            field=models.CharField(choices=[('N', 'Not Available'), ('SHR', 'Shared'), ('SEP', 'Separated')], default='SEP', max_length=5),
        ),
    ]
