# Generated by Django 4.1.3 on 2022-12-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_kitchen_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='type',
            field=models.CharField(choices=[('N', 'Not Available'), ('SEP', 'Separated'), ('AT', 'Attached')], default='SEP', max_length=5),
        ),
    ]
