# Generated by Django 4.1.3 on 2022-12-08 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_bathroom_property_alter_kitchen_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='numbers',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
