# Generated by Django 4.1.3 on 2022-12-08 14:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_bedroom_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='numbers',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
