# Generated by Django 4.1.3 on 2022-12-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_bedroom_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
