# Generated by Django 4.1.3 on 2022-12-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_bedroom_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroomimage',
            name='bedroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.bedroom'),
        ),
    ]
