# Generated by Django 4.1.3 on 2022-12-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.CharField(choices=[('NONE', 'None'), ('2W', 'Two Wheeler'), ('4W', 'Four Wheeler')], default='1BHK', max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='water',
            field=models.CharField(choices=[('NONE', 'None'), ('A', 'Anytime'), ('B', 'Boring Water'), ('T', 'Tank Water')], default='NONE', max_length=5),
        ),
    ]
