# Generated by Django 4.1.3 on 2022-12-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_property_parking_alter_property_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, default='static/image/city.jpeg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='bedroomimage',
            name='image',
            field=models.ImageField(blank=True, default='static/image/city.jpeg', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
