# Generated by Django 4.1.3 on 2022-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_featured_image_alter_bedroomimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, default='image/city.jpeg', upload_to='image/'),
        ),
    ]
