# Generated by Django 4.1.3 on 2022-12-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_bathroom_image_alter_property_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='image',
            field=models.ImageField(blank=True, default='image/noimage.png', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(blank=True, default='image/noimage.png', upload_to='image/'),
        ),
    ]
