# Generated by Django 4.1.3 on 2022-12-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_alter_bathroom_image_alter_kitchen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroomimage',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
