# Generated by Django 4.1.3 on 2022-12-30 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_type'),
        ('properties', '0024_alter_property_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reservations',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.tenantuserprofile')),
            ],
        ),
    ]
