# Generated by Django 4.1.3 on 2022-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('AGENT', 'Agent')], max_length=50),
        ),
    ]
