# Generated by Django 4.1.3 on 2022-12-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_agentuserprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image/user.png', upload_to='image/'),
        ),
    ]
