# Generated by Django 4.1.3 on 2022-12-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_agentuserprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('A', 'Agent'), ('T', 'Tenant'), ('N', 'Not assigned')], default='N', max_length=5),
        ),
    ]
